version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - OUTPUT_DIR=/app/downloads
      - TASK_RETENTION=24h
    volumes:
      - .:/app
      - download-data:/app/downloads
      - go-modules:/go/pkg/mod
      - venv-data:/app/venv
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
  download-data:
  go-modules:
  venv-data:
